### ISSUE TITLE
The Architect Works Slider

### ISSUE THREAD

**Issue by ressan0515** [zarigani-design-office/the-architect#1]
度々お問い合わせさせていただき、申し訳ございません。
もし、ご回答いただけるようでしたら、お願いいたします。

Word PressテンプレートThe Architectを使用させていただいております。
WORKSの新規作成を行い、画像ギャラリーを作成しましたが、
サイト上での表示が、デモのようなスライダーになりません。
スライダーを表示するために必要な設定がございましたら、ご教示いただけますと幸いです。

お忙しいところ、失礼いたします。

**Comment by zarigani-design-office** [comment]
テーマ内のバグが原因でした。
version 0.9.8にて当該バグを修正しましたので、お手数ですがアップデートをお願いいたします。
