### ISSUE TITLE
WORKS Slider

### ISSUE THREAD

**Issue by hertta4** [zarigani-design-office/the-architect#2]
WORKSの新規作成をすると、PCでは正常にスライダーが表示されるのですが、タブレット以下ではスライダーが画面からはみ出してしまいます。
デモのWORKSのなかで、「Tjuvholmen F1」もそのように表示されます。デモの他のWORKSは画面幅に合わせて調整されました。

**Comment by zarigani-design-office** [comment]
[最新版](https://github.com/zarigani-design-office/the-architect/releases/tag/0.9.8.2)にて修正されました。
