### ISSUE TITLE
初期設定　表示名設定が無効

### ISSUE THREAD

**Issue by ressan05** [zarigani-design-office/the-architect#3]
初期設定　表示名設定が無効

WORKS 表示名と　BLOG　表示名をそれぞれ変更したが、サイトのTOPページの表示に反映されず、
WORKS、BLOGのままの表示となる。

**Comment by zarigani-design-office** [comment]
[最新版](https://github.com/zarigani-design-office/the-architect/releases/tag/0.9.8.2)にて修正されました。
